version: '3.3'
services:
  nginx:
    image: "openresty/openresty:alpine"
    volumes:
      - ./www:/usr/local/openresty/nginx/app
      - ./etc/openresty/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./run:/var/run/
    ports:
      - 0.0.0.0:80:80

  php-fpm:
    build: php-fpm_pgsql
    volumes:
      - ./etc/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./etc/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./run:/var/run/
      - ./www:/var/www/html

  postgres:
    image: "postgres:alpine"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./run:/var/run/postgresql